/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVocabularyRouteImport } from './routes/_authenticated/vocabulary'
import { Route as AuthenticatedUniversityRouteImport } from './routes/_authenticated/university'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedGermanyJourneyRouteImport } from './routes/_authenticated/germany-journey'
import { Route as AuthenticatedGermanRouteImport } from './routes/_authenticated/german'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedBlogRouteImport } from './routes/_authenticated/blog'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings.ai'
import { Route as AuthenticatedAssistantReviewRouteImport } from './routes/_authenticated/assistant.review'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVocabularyRoute = AuthenticatedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUniversityRoute = AuthenticatedUniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGermanyJourneyRoute =
  AuthenticatedGermanyJourneyRouteImport.update({
    id: '/germany-journey',
    path: '/germany-journey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGermanRoute = AuthenticatedGermanRouteImport.update({
  id: '/german',
  path: '/german',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlogRoute = AuthenticatedBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSettingsRoute,
} as any)
const AuthenticatedAssistantReviewRoute =
  AuthenticatedAssistantReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/blog': typeof AuthenticatedBlogRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/german': typeof AuthenticatedGermanRoute
  '/germany-journey': typeof AuthenticatedGermanyJourneyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/tools': typeof AuthenticatedToolsRoute
  '/university': typeof AuthenticatedUniversityRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/assistant/review': typeof AuthenticatedAssistantReviewRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/blog': typeof AuthenticatedBlogRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/german': typeof AuthenticatedGermanRoute
  '/germany-journey': typeof AuthenticatedGermanyJourneyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/tools': typeof AuthenticatedToolsRoute
  '/university': typeof AuthenticatedUniversityRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/assistant/review': typeof AuthenticatedAssistantReviewRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/_authenticated/blog': typeof AuthenticatedBlogRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/german': typeof AuthenticatedGermanRoute
  '/_authenticated/germany-journey': typeof AuthenticatedGermanyJourneyRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/university': typeof AuthenticatedUniversityRoute
  '/_authenticated/vocabulary': typeof AuthenticatedVocabularyRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/assistant/review': typeof AuthenticatedAssistantReviewRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/blog'
    | '/budget'
    | '/calendar'
    | '/check-in'
    | '/dashboard'
    | '/feedback'
    | '/german'
    | '/germany-journey'
    | '/onboarding'
    | '/portfolio'
    | '/settings'
    | '/tools'
    | '/university'
    | '/vocabulary'
    | '/admin/dashboard'
    | '/admin/users'
    | '/assistant/review'
    | '/settings/ai'
    | '/settings/notifications'
    | '/settings/security'
    | '/api/ai/chat'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/analytics'
    | '/assistant'
    | '/blog'
    | '/budget'
    | '/calendar'
    | '/check-in'
    | '/dashboard'
    | '/feedback'
    | '/german'
    | '/germany-journey'
    | '/onboarding'
    | '/portfolio'
    | '/settings'
    | '/tools'
    | '/university'
    | '/vocabulary'
    | '/admin/dashboard'
    | '/admin/users'
    | '/assistant/review'
    | '/settings/ai'
    | '/settings/notifications'
    | '/settings/security'
    | '/api/ai/chat'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/assistant'
    | '/_authenticated/blog'
    | '/_authenticated/budget'
    | '/_authenticated/calendar'
    | '/_authenticated/check-in'
    | '/_authenticated/dashboard'
    | '/_authenticated/feedback'
    | '/_authenticated/german'
    | '/_authenticated/germany-journey'
    | '/_authenticated/onboarding'
    | '/_authenticated/portfolio'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/university'
    | '/_authenticated/vocabulary'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/users'
    | '/_authenticated/assistant/review'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/security'
    | '/api/ai/chat'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vocabulary': {
      id: '/_authenticated/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthenticatedVocabularyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/university': {
      id: '/_authenticated/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof AuthenticatedUniversityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/germany-journey': {
      id: '/_authenticated/germany-journey'
      path: '/germany-journey'
      fullPath: '/germany-journey'
      preLoaderRoute: typeof AuthenticatedGermanyJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/german': {
      id: '/_authenticated/german'
      path: '/german'
      fullPath: '/german'
      preLoaderRoute: typeof AuthenticatedGermanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog': {
      id: '/_authenticated/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/assistant/review': {
      id: '/_authenticated/assistant/review'
      path: '/review'
      fullPath: '/assistant/review'
      preLoaderRoute: typeof AuthenticatedAssistantReviewRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAssistantRouteChildren {
  AuthenticatedAssistantReviewRoute: typeof AuthenticatedAssistantReviewRoute
}

const AuthenticatedAssistantRouteChildren: AuthenticatedAssistantRouteChildren =
  {
    AuthenticatedAssistantReviewRoute: AuthenticatedAssistantReviewRoute,
  }

const AuthenticatedAssistantRouteWithChildren =
  AuthenticatedAssistantRoute._addFileChildren(
    AuthenticatedAssistantRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRouteWithChildren
  AuthenticatedBlogRoute: typeof AuthenticatedBlogRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedGermanRoute: typeof AuthenticatedGermanRoute
  AuthenticatedGermanyJourneyRoute: typeof AuthenticatedGermanyJourneyRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedUniversityRoute: typeof AuthenticatedUniversityRoute
  AuthenticatedVocabularyRoute: typeof AuthenticatedVocabularyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRouteWithChildren,
  AuthenticatedBlogRoute: AuthenticatedBlogRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedGermanRoute: AuthenticatedGermanRoute,
  AuthenticatedGermanyJourneyRoute: AuthenticatedGermanyJourneyRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedUniversityRoute: AuthenticatedUniversityRoute,
  AuthenticatedVocabularyRoute: AuthenticatedVocabularyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAiChatRoute: ApiAiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
